//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolodvorApp.Client.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KolodvorApp.Client.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KolodvorApp.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Data.
        /// </summary>
        public static string NAV_MENU_FETCH_DATA {
            get {
                return ResourceManager.GetString("NAV_MENU_FETCH_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NAV_MENU_HOME {
            get {
                return ResourceManager.GetString("NAV_MENU_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Overview.
        /// </summary>
        public static string NAV_MENU_TRAINS {
            get {
                return ResourceManager.GetString("NAV_MENU_TRAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open train details.
        /// </summary>
        public static string OPEN_TRAIN_DETAILS {
            get {
                return ResourceManager.GetString("OPEN_TRAIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAIN OVERVIEW.
        /// </summary>
        public static string PAGE_TITLE_TRAIN_OVERVIEW {
            get {
                return ResourceManager.GetString("PAGE_TITLE_TRAIN_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string TABLE_CAPACITY {
            get {
                return ResourceManager.GetString("TABLE_CAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TABLE_CATEGORIES {
            get {
                return ResourceManager.GetString("TABLE_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string TABLE_COST {
            get {
                return ResourceManager.GetString("TABLE_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string TABLE_MAINTENANCE {
            get {
                return ResourceManager.GetString("TABLE_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string TABLE_TAG {
            get {
                return ResourceManager.GetString("TABLE_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string TABLE_TOTAL_COST {
            get {
                return ResourceManager.GetString("TABLE_TOTAL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train .
        /// </summary>
        public static string TRAIN_DIALOG_TITLE_1 {
            get {
                return ResourceManager.GetString("TRAIN_DIALOG_TITLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  detail view.
        /// </summary>
        public static string TRAIN_DIALOG_TITLE_2 {
            get {
                return ResourceManager.GetString("TRAIN_DIALOG_TITLE_2", resourceCulture);
            }
        }
    }
}
